name: Lint and Install Required Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out the code
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mongo
        pip install -r requirements.txt
    - name: Run Pylint
      run: |
        pylint $(git ls-files '*.py')  # Run Pylint on Python files
