name: Lint and Install Required Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out the code
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo==4.11.2
        # Extract all required packages (both simple imports and from xx import yy)
        # First, we capture both forms of imports: 'import xx' and 'from xx import yy'
        required_packages=$(grep -hoP "(?<=import\s)(\w+)" $(git ls-files '*.py') | sort | uniq)
        required_packages+=$(grep -hoP "(?<=from\s)(\w+)(?=\simport)" $(git ls-files '*.py') | sort | uniq)
        
        # Install all required packages (install xx for 'from xx import yy' cases)
        for package in $required_packages; do
          pip install "$package"  # Install the required packages
        done
    - name: Run Pylint
      run: |
        pylint $(git ls-files '*.py')  # Run Pylint on Python files
